### ISSUE TITLE
Example failes to run

### ISSUE THREAD

**Issue by tadam98** [RahulShagri/OG-Tetris-Game#1]
requirements.txt contails outdated packages.
```
dearpygui==0.8.57
pandas==1.3.1
playsound2==0.1
```
It is on Windows 10 Version 21H1 (OS Build 19043.1288), conda environment with python 7.3.10. VisualCode 1.6.1.2
**dearpygui-1.0.2
playsound-1.3.0
pandas 1.15.0**

Anyway, executing tetris_gain.py does not open any form.

**Comment by RahulShagri** [comment]
Sorry, I haven't updated the code since the latest Dear PyGui version came out.

**Comment by tadam98** [comment]
Please do as you are staaring here: [https://preettheman.medium.com/this-new-python-package-builds-awesome-guis-150defda7915](url)

**Comment by RahulShagri** [comment]
The app has been updated to run on the latest version of DPG now! Closing the issue.
